### ISSUE TITLE
bug in jsonapi serializer

### ISSUE THREAD

**Issue by jamesdixon** [scoutforpets/jsonapi-mapper#48] opened 2016-07-07 22:18 UTC
There's an issue in the latest version of the JSON API serializer that is causing empty relations to be returned. I've submitted a PR, but there hasn't been any movement on the repo in quite some time. We may want to consider switching to my fork until the issue is resolved in the parent repo.

**Comment by chamini2** [comment] 2016-07-07 22:31
So the problem is with the JSON API serlaizer? I thought it was in the jsonapi-mapper. Great to know.

**Comment by chamini2** [comment] 2016-07-07 22:31
I say we switch to you fork and open an issue to re-switch when the PR is merged.

**Comment by jamesdixon** [comment] 2016-07-07 22:32
I did at first as well, but downgrading the serializer resolved the issue. https://github.com/SeyZ/jsonapi-serializer/pull/94

**Closed** 2016-07-07 23:35 UTC

**Comment by jamesdixon** [comment] 2016-07-07 23:38
Released 0.9.0 which contains the switch to the fork and some other fixes that we had pushed but never published

**Comment by chamini2** [comment] 2016-07-14 16:23
Hey @jamesdixon, I tried the version 0.9.0 and for an empty relation it returns `data: null`, is this the expected behaviour?

**Comment by jamesdixon** [comment] 2016-07-14 17:56
@chamini2 I actually wasn't able to reproduce that on my end. I tested with 0.8.0 and looked at the output of my failing test, which resulted in the following: `relationships: {}`. After upgrading to 0.9.0, I no longer see the `relationships` key.

That said, `data: null` is actually a valid value for an *empty* relationship. That said, is it possible that the relationship exists on your end, but is empty?

**Comment by chamini2** [comment] 2016-07-14 17:58
It resulted in

```js
relationships: {
  'some-relation': {
    data: null,
    links : { /* link data here */ }
  }
}
```

**Comment by jamesdixon** [comment] 2016-07-14 18:12
Let me know what you discover

**Comment by ShadowManu** [comment] 2016-08-01 11:25
The accepted solution was to use a fork on a stable version of the serializer project. What's the soon-future on this?

**Comment by jamesdixon** [comment] 2016-08-01 19:49
@ShadowManu my fix was finally merged into the official repo. We can switch on our next release

**Comment by ShadowManu** [comment] 2016-08-01 21:42
From which `jsonapi-serializer` starting version does the fix is available? Or TBA?

**Comment by jamesdixon** [comment] 2016-08-01 21:43
3.3.0
